apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: ebs-sc
parameters: 
   type: gp3 
reclaimPolicy: Retain 
allowVolumeExpansion: true
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer